export const data = {
  nodes: [
    {
      id: 1,
      value: 1,
      moves:[6,4],
      neighbors: [2, 3],      
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 2,
      value: 1,
      moves:[7,9],
      neighbors: [4, 5],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 3,
      value: 1,
      moves:[8,10],
      neighbors: [5, 6],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 4,
      value: 1,
      moves:[1,6,11,13],
      neighbors: [2, 5, 7, 8],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 5,
      value: 1,
      moves:[12,14],
      neighbors: [8, 9],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 6,
      value: 1,
      moves:[1,4,13,15],
      neighbors: [3, 5, 9, 10],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 7,
      value: 1,
      moves:[2,9],
      neighbors: [4, 8],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 8,
      value: 1,
      moves:[3,10],
      neighbors: [9, 5],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 9,
      value: 1,
      moves:[2,7],
      neighbors: [8, 5],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 10,
      value: 1,
      moves:[3,8],
      neighbors: [6, 9],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 11,
      value: 1,
      moves:[4,13],
      neighbors: [7, 12],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 12,
      value: 1,
      moves:[5,14],
      neighbors: [8, 13],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 13,
      value: 1,
      moves:[4,11,6,15],
      neighbors: [8, 9, 12, 14],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 14,
      value: 1,
      moves:[5,12],      
      neighbors: [13, 9],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
    {
      id: 15,
      value: 1,
      moves:[6,13],
      neighbors: [10, 14],     
      active:'N',
      displayValue:'T',
      flag:'',
      stylename:'bttn',
    },
  ],
};
